import Foundation

// ═══════════════════════════════════════════════════════════
// MARK: - DebugInfoParser
// ═══════════════════════════════════════════════════════════

/// Parses `.dbg` files generated by ca65/ld65 to map source lines
/// to memory addresses for source-level debugging.
///
/// `.dbg` format summary:
///   - `file`: Source file definitions with IDs
///   - `seg`: Segment definitions with start addresses
///   - `span`: Byte ranges within segments (offset + size)
///   - `line`: Source file line → span mapping
///   - `sym`: Symbol names → addresses
///
/// The parser builds bidirectional mappings (`lineToAddress` and `addressToLine`)
/// to enable IDE features like breakpoint setting and source highlighting.
class DebugInfoParser {

    // Parsed data
    private(set) var files: [Int: DebugFile] = [:]
    private(set) var segments: [Int: DebugSegment] = [:]
    private(set) var spans: [Int: DebugSpan] = [:]
    private(set) var lines: [DebugLine] = []
    private(set) var symbols: [DebugSymbol] = []

    // Derived mappings
    private(set) var lineToAddress: [Int: UInt16] = [:]      // source line → memory address
    private(set) var addressToLine: [UInt16: Int] = [:]       // memory address → source line
    private(set) var symbolsByName: [String: DebugSymbol] = [:]
    private(set) var symbolsByAddress: [UInt16: DebugSymbol] = [:]

    // MARK: - Parsing

    /// Parses a `.dbg` file and returns a configured parser instance.
    /// Returns `nil` if the file cannot be read.
    static func parse(contentsOf url: URL) -> DebugInfoParser? {
        guard let content = try? String(contentsOf: url, encoding: .utf8) else { return nil }
        let parser = DebugInfoParser()
        parser.parseContent(content)
        return parser
    }

    /// Parses a `.dbg` format string and returns a configured parser instance.
    static func parse(string: String) -> DebugInfoParser {
        let parser = DebugInfoParser()
        parser.parseContent(string)
        return parser
    }

    private func parseContent(_ content: String) {
        for rawLine in content.components(separatedBy: "\n") {
            let line = rawLine.trimmingCharacters(in: .whitespaces)
            guard !line.isEmpty else { continue }

            // Split into type and attributes
            guard let tabIndex = line.firstIndex(of: "\t") else { continue }
            let type = String(line[line.startIndex..<tabIndex])
            let attrs = String(line[line.index(after: tabIndex)...])
            let props = parseAttributes(attrs)

            switch type {
            case "file":    parseFile(props)
            case "seg":     parseSegment(props)
            case "span":    parseSpan(props)
            case "line":    parseLine(props)
            case "sym":     parseSymbol(props)
            default: break
            }
        }

        buildMappings()
    }

    // MARK: - Attribute Parser

    /// Parses `key=value,key=value,...` into a dictionary.
    /// Handles both quoted and unquoted values correctly.
    private func parseAttributes(_ str: String) -> [String: String] {
        var result: [String: String] = [:]

        var current = str.startIndex
        while current < str.endIndex {
            // Find key
            guard let eqIdx = str[current...].firstIndex(of: "=") else { break }
            let key = String(str[current..<eqIdx]).trimmingCharacters(in: .whitespaces)
            var valueStart = str.index(after: eqIdx)

            var value: String
            if valueStart < str.endIndex && str[valueStart] == "\"" {
                // Quoted value
                valueStart = str.index(after: valueStart)
                if let closeQuote = str[valueStart...].firstIndex(of: "\"") {
                    value = String(str[valueStart..<closeQuote])
                    current = str.index(after: closeQuote)
                } else {
                    value = String(str[valueStart...])
                    current = str.endIndex
                }
            } else {
                // Unquoted value — read until comma
                if let commaIdx = str[valueStart...].firstIndex(of: ",") {
                    value = String(str[valueStart..<commaIdx])
                    current = str.index(after: commaIdx)
                } else {
                    value = String(str[valueStart...])
                    current = str.endIndex
                }
            }

            result[key] = value

            // Skip comma
            if current < str.endIndex && str[current] == "," {
                current = str.index(after: current)
            }
        }

        return result
    }

    // MARK: - Entry Parsers

    private func parseFile(_ props: [String: String]) {
        guard let id = intVal(props["id"]),
              let name = props["name"] else { return }
        files[id] = DebugFile(id: id, name: name)
    }

    private func parseSegment(_ props: [String: String]) {
        guard let id = intVal(props["id"]),
              let name = props["name"],
              let start = hexVal(props["start"]),
              let size = hexVal(props["size"]) else { return }
        segments[id] = DebugSegment(id: id, name: name, start: UInt16(start), size: Int(size))
    }

    private func parseSpan(_ props: [String: String]) {
        guard let id = intVal(props["id"]),
              let seg = intVal(props["seg"]),
              let start = intVal(props["start"]),
              let size = intVal(props["size"]) else { return }
        spans[id] = DebugSpan(id: id, segmentId: seg, offset: start, size: size)
    }

    private func parseLine(_ props: [String: String]) {
        guard let fileId = intVal(props["file"]),
              let lineNum = intVal(props["line"]) else { return }
        let spanId = intVal(props["span"])
        lines.append(DebugLine(fileId: fileId, lineNumber: lineNum, spanId: spanId))
    }

    private func parseSymbol(_ props: [String: String]) {
        guard let name = props["name"],
              let val = hexVal(props["val"]) else { return }
        let segId = intVal(props["seg"])
        let size = intVal(props["size"])
        let sym = DebugSymbol(name: name, address: UInt16(val), segmentId: segId, size: size)
        symbols.append(sym)
    }

    // MARK: - Build Mappings

    private func buildMappings() {
        lineToAddress.removeAll()
        addressToLine.removeAll()
        symbolsByName.removeAll()
        symbolsByAddress.removeAll()

        // Build line → address mapping
        for line in lines {
            guard let spanId = line.spanId,
                  let span = spans[spanId],
                  let seg = segments[span.segmentId] else { continue }

            let address = seg.start &+ UInt16(span.offset)

            // Only map if we don't have a mapping for this line yet,
            // or if this address is lower (first instruction on the line)
            if lineToAddress[line.lineNumber] == nil || address < lineToAddress[line.lineNumber]! {
                lineToAddress[line.lineNumber] = address
            }

            // Reverse mapping (prefer lower line numbers for the same address)
            if addressToLine[address] == nil || line.lineNumber < addressToLine[address]! {
                addressToLine[address] = line.lineNumber
            }
        }

        // Build symbol mappings
        for sym in symbols {
            symbolsByName[sym.name] = sym
            // Only store non-local symbols (skip @ prefixed)
            if !sym.name.hasPrefix("@") {
                symbolsByAddress[sym.address] = sym
            }
        }
    }

    // MARK: - Queries

    /// Returns the memory address for a given source line number.
    func addressForLine(_ line: Int) -> UInt16? {
        return lineToAddress[line]
    }

    /// Returns the source line for a given memory address.
    ///
    /// Performs an exact match first. If none exists, finds the closest
    /// address that is `≤` the given address, enabling approximate source
    /// highlighting for ranges spanning multiple instructions.
    func lineForAddress(_ address: UInt16) -> Int? {
        // Exact match first
        if let line = addressToLine[address] { return line }

        // Find the closest address that's ≤ the given address
        var bestLine: Int?
        var bestAddr: UInt16 = 0
        for (addr, line) in addressToLine {
            if addr <= address && addr >= bestAddr {
                bestAddr = addr
                bestLine = line
            }
        }
        return bestLine
    }

    /// Returns the address for a named symbol.
    func addressForSymbol(_ name: String) -> UInt16? {
        return symbolsByName[name]?.address
    }

    /// Returns all symbols defined within a specific segment.
    func symbolsInSegment(_ name: String) -> [DebugSymbol] {
        guard let seg = segments.values.first(where: { $0.name == name }) else { return [] }
        return symbols.filter { $0.segmentId == seg.id }
    }

    /// Converts editor breakpoint line numbers to memory addresses.
    func breakpointAddresses(forLines editorLines: Set<Int>) -> [UInt16] {
        var addresses: [UInt16] = []
        for line in editorLines.sorted() {
            if let addr = addressForLine(line) {
                addresses.append(addr)
            }
        }
        return addresses
    }

    /// Generates a VICE monitor commands file with breakpoints and labels.
    func generateMonitorCommands(breakpointLines: Set<Int>, entryPoint: UInt16? = nil) -> String {
        var cmds: [String] = ["; C64 IDE debug symbols"]

        // Add labels for all non-local symbols
        for sym in symbols where !sym.name.hasPrefix("@") {
            cmds.append(String(format: "al C:%04X .%@", sym.address, sym.name))
        }

        cmds.append("")

        // Entry point breakpoint
        if let entry = entryPoint {
            cmds.append(String(format: "break $%04x", entry))
        }

        // Editor breakpoints mapped to addresses
        for line in breakpointLines.sorted() {
            if let addr = addressForLine(line) {
                cmds.append(String(format: "break $%04x  ; line %d", addr, line))
            }
        }

        return cmds.joined(separator: "\n") + "\n"
    }

    /// Returns a summary string of the parsed debug information.
    var summary: String {
        let lineCount = lineToAddress.count
        let symCount = symbols.filter { !$0.name.hasPrefix("@") }.count
        let segNames = segments.values.map { $0.name }.joined(separator: ", ")
        return "\(lineCount) line mappings, \(symCount) symbols, segments: \(segNames)"
    }

    // MARK: - Helpers

    private func intVal(_ str: String?) -> Int? {
        guard let s = str else { return nil }
        if s.hasPrefix("0x") || s.hasPrefix("0X") {
            return Int(s.dropFirst(2), radix: 16)
        }
        return Int(s)
    }

    private func hexVal(_ str: String?) -> Int? {
        guard let s = str else { return nil }
        if s.hasPrefix("0x") || s.hasPrefix("0X") {
            return Int(s.dropFirst(2), radix: 16)
        }
        return Int(s, radix: 16) ?? Int(s)
    }
}

// ═══════════════════════════════════════════════════════════
// MARK: - Data Structures
// ═══════════════════════════════════════════════════════════

/// Represents a source file referenced in the `.dbg` file.
struct DebugFile {
    let id: Int
    let name: String
}

/// Represents a memory segment (e.g., CODE, BSS, DATA).
struct DebugSegment {
    let id: Int
    let name: String
    let start: UInt16
    let size: Int
}

/// Represents a contiguous byte range within a segment.
struct DebugSpan {
    let id: Int
    let segmentId: Int
    let offset: Int
    let size: Int
}

/// Maps a source line to a span.
struct DebugLine {
    let fileId: Int
    let lineNumber: Int
    let spanId: Int?
}

/// Represents a symbol (variable, function, label) with its address.
struct DebugSymbol {
    let name: String
    let address: UInt16
    let segmentId: Int?
    let size: Int?
}

