import Foundation

// ═══════════════════════════════════════════════════════════
// MARK: - DebugInfoParser
// ═══════════════════════════════════════════════════════════

/// Parses `.dbg` files generated by ca65/ld65 to map source lines
/// to memory addresses for source-level debugging.
///
/// `.dbg` format summary:
///   - `file`: Source file definitions with IDs
///   - `seg`: Segment definitions with start addresses
///   - `span`: Byte ranges within segments (offset + size)
///   - `line`: Source file line → span mapping
///   - `sym`: Symbol names → addresses
///
/// The parser builds bidirectional mappings (`fileLineToAddress` and
/// `addressToLocation`), keyed by (file, line) so multi-file projects
/// (.include) don't collide, to enable IDE features like breakpoint
/// setting and source highlighting.
class DebugInfoParser {

    // Parsed data
    private(set) var files: [Int: DebugFile] = [:]
    private(set) var segments: [Int: DebugSegment] = [:]
    private(set) var spans: [Int: DebugSpan] = [:]
    private(set) var lines: [DebugLine] = []
    private(set) var symbols: [DebugSymbol] = []

    // Derived mappings
    private(set) var fileLineToAddress: [SourceLocation: UInt16] = [:]  // (file, line) → memory address
    private(set) var addressToLocation: [UInt16: SourceLocation] = [:]  // memory address → (file, line)

    /// Every mapped span as an inclusive address range, sorted by `start`.
    /// Backs `location(forAddress:)`, which needs *containment* rather than
    /// "nearest preceding address" — see that method for why.
    private var sortedSpans: [MappedSpan] = []

    /// Length of the widest entry in `sortedSpans`. Bounds how far back a
    /// containment search has to walk from its binary-search landing point.
    private var maxSpanLength: Int = 0

    /// The file assumed when no explicit file is given (editor breakpoints,
    /// highlight callbacks). Defaults to the file contributing the most line
    /// mappings, which in practice is the main source. Override with
    /// `setPrimaryFile(named:)`.
    private(set) var primaryFileId: Int?
    private(set) var symbolsByName: [String: DebugSymbol] = [:]

    // MARK: - Parsing

    /// Parses a `.dbg` file and returns a configured parser instance.
    /// Returns `nil` if the file cannot be read.
    static func parse(contentsOf url: URL) -> DebugInfoParser? {
        guard let content = try? String(contentsOf: url, encoding: .utf8) else { return nil }
        let parser = DebugInfoParser()
        parser.parseContent(content)
        return parser
    }

    /// Parses a `.dbg` format string and returns a configured parser instance.
    static func parse(string: String) -> DebugInfoParser {
        let parser = DebugInfoParser()
        parser.parseContent(string)
        return parser
    }

    private func parseContent(_ content: String) {
        for rawLine in content.components(separatedBy: "\n") {
            let line = rawLine.trimmingCharacters(in: .whitespaces)
            guard !line.isEmpty else { continue }

            // Split into type and attributes
            guard let tabIndex = line.firstIndex(of: "\t") else { continue }
            let type = String(line[line.startIndex..<tabIndex])
            let attrs = String(line[line.index(after: tabIndex)...])
            let props = parseAttributes(attrs)

            switch type {
            case "file":    parseFile(props)
            case "seg":     parseSegment(props)
            case "span":    parseSpan(props)
            case "line":    parseLine(props)
            case "sym":     parseSymbol(props)
            default: break
            }
        }

        buildMappings()
    }

    // MARK: - Attribute Parser

    /// Parses `key=value,key=value,...` into a dictionary.
    /// Handles both quoted and unquoted values correctly.
    private func parseAttributes(_ str: String) -> [String: String] {
        var result: [String: String] = [:]

        var current = str.startIndex
        while current < str.endIndex {
            // Find key
            guard let eqIdx = str[current...].firstIndex(of: "=") else { break }
            let key = String(str[current..<eqIdx]).trimmingCharacters(in: .whitespaces)
            var valueStart = str.index(after: eqIdx)

            var value: String
            if valueStart < str.endIndex && str[valueStart] == "\"" {
                // Quoted value
                valueStart = str.index(after: valueStart)
                if let closeQuote = str[valueStart...].firstIndex(of: "\"") {
                    value = String(str[valueStart..<closeQuote])
                    current = str.index(after: closeQuote)
                } else {
                    value = String(str[valueStart...])
                    current = str.endIndex
                }
            } else {
                // Unquoted value — read until comma
                if let commaIdx = str[valueStart...].firstIndex(of: ",") {
                    value = String(str[valueStart..<commaIdx])
                    current = str.index(after: commaIdx)
                } else {
                    value = String(str[valueStart...])
                    current = str.endIndex
                }
            }

            result[key] = value

            // Skip comma
            if current < str.endIndex && str[current] == "," {
                current = str.index(after: current)
            }
        }

        return result
    }

    // MARK: - Entry Parsers

    private func parseFile(_ props: [String: String]) {
        guard let id = intVal(props["id"]),
              let name = props["name"] else { return }
        files[id] = DebugFile(id: id, name: name)
    }

    private func parseSegment(_ props: [String: String]) {
        // `size` is deliberately not required: a segment missing it would
        // otherwise be dropped, silently unmapping every line inside it.
        guard let id = intVal(props["id"]),
              let name = props["name"],
              let start = hexVal(props["start"]),
              // Out-of-range start would trap UInt16(start); skip such segments
              (0...0xFFFF).contains(start) else { return }
        segments[id] = DebugSegment(id: id, name: name, start: UInt16(start))
    }

    private func parseSpan(_ props: [String: String]) {
        guard let id = intVal(props["id"]),
              let seg = intVal(props["seg"]),
              let start = intVal(props["start"]) else { return }
        spans[id] = DebugSpan(id: id, segmentId: seg, offset: start,
                              size: intVal(props["size"]) ?? 0)
    }

    private func parseLine(_ props: [String: String]) {
        guard let fileId = intVal(props["file"]),
              let lineNum = intVal(props["line"]) else { return }
        // ld65 emits multi-span lines as `span=286+287` (common with macros).
        // Parse every span so none of the line's code goes unmapped.
        let spanIds = props["span"]?
            .split(separator: "+")
            .compactMap { intVal(String($0)) } ?? []
        lines.append(DebugLine(fileId: fileId, lineNumber: lineNum, spanIds: spanIds))
    }

    private func parseSymbol(_ props: [String: String]) {
        // ca65 equates can be 32-bit or negative (stored as large hex values).
        // Anything outside the 6502 address space can't be a label or
        // breakpoint target and would trap UInt16(val), so skip it.
        guard let name = props["name"],
              let val = hexVal(props["val"]),
              (0...0xFFFF).contains(val) else { return }
        symbols.append(DebugSymbol(name: name, address: UInt16(val),
                                   segmentId: intVal(props["seg"])))
    }

    // MARK: - Build Mappings

    private func buildMappings() {
        fileLineToAddress.removeAll()
        addressToLocation.removeAll()
        symbolsByName.removeAll()
        sortedSpans.removeAll()
        maxSpanLength = 0

        // ── Pass 1: (file, line) → address, and the span range table ──
        for line in lines {
            for spanId in line.spanIds {
                guard let span = spans[spanId],
                      let seg = segments[span.segmentId] else { continue }

                // Compute in Int so a corrupt or oversized offset can't
                // trap UInt16(); addresses past $FFFF are skipped.
                let addrInt = Int(seg.start) + span.offset
                guard (0...0xFFFF).contains(addrInt) else { continue }
                let address = UInt16(addrInt)

                let loc = SourceLocation(fileId: line.fileId, line: line.lineNumber)

                // Only map if we don't have a mapping for this line yet,
                // or if this address is lower (first instruction on the line)
                if let existing = fileLineToAddress[loc] {
                    if address < existing { fileLineToAddress[loc] = address }
                } else {
                    fileLineToAddress[loc] = address
                }

                // A zero/absent span size still covers at least the
                // instruction that starts there; 3 is the widest 6502
                // instruction, so a PC landing mid-instruction still resolves.
                let length = span.size > 0 ? span.size : 3
                let endInt = min(addrInt + length - 1, 0xFFFF)
                sortedSpans.append(MappedSpan(start: address, end: UInt16(endInt), location: loc))
                maxSpanLength = max(maxSpanLength, endInt - addrInt + 1)
            }
        }

        sortedSpans.sort { $0.start < $1.start }

        // Default primary file: the one contributing the most line mappings.
        // (A user-set primary file survives re-parsing only if it still exists.)
        if primaryFileId == nil || files[primaryFileId!] == nil {
            var counts: [Int: Int] = [:]
            for loc in fileLineToAddress.keys { counts[loc.fileId, default: 0] += 1 }
            primaryFileId = counts.max(by: { $0.value < $1.value })?.key
        }

        // ── Pass 2: address → (file, line) ──
        // Deferred until `primaryFileId` is known so the tie-break can prefer
        // it. Comparing raw line numbers across different files (the previous
        // rule) picked an arbitrary winner, since line 12 of an include has no
        // ordering relationship to line 12 of the main source.
        for span in sortedSpans {
            guard let existing = addressToLocation[span.start] else {
                addressToLocation[span.start] = span.location
                continue
            }
            if preferredLocation(existing, span.location) == span.location {
                addressToLocation[span.start] = span.location
            }
        }

        // Build symbol mappings
        for sym in symbols {
            symbolsByName[sym.name] = sym
        }
    }

    /// Picks the better of two locations claiming the same address:
    /// the primary file wins, then the lower line number within one file,
    /// then the lower file ID so the result is at least deterministic.
    private func preferredLocation(_ a: SourceLocation, _ b: SourceLocation) -> SourceLocation {
        if a.fileId != b.fileId {
            if a.fileId == primaryFileId { return a }
            if b.fileId == primaryFileId { return b }
            return a.fileId <= b.fileId ? a : b
        }
        return a.line <= b.line ? a : b
    }

    // MARK: - Queries

    /// Returns the memory address for a source line. When `fileId` is nil,
    /// the primary file is assumed (i.e. editor breakpoints in the main source).
    func addressForLine(_ line: Int, fileId: Int? = nil) -> UInt16? {
        guard let fid = fileId ?? primaryFileId else { return nil }
        return fileLineToAddress[SourceLocation(fileId: fid, line: line)]
    }

    /// Returns the source location (file + line) whose emitted code *contains*
    /// `address`, or `nil` when the address isn't part of the built program.
    ///
    /// Containment matters. The old rule — "nearest mapped address ≤ this one,
    /// searched without bound" — meant a PC anywhere outside the program
    /// (KERNAL ROM, an IRQ vector, a stray jump) resolved to the last line of
    /// the source and highlighted it in the editor. Returning `nil` lets the
    /// caller clear the highlight instead of pointing at innocent code.
    ///
    /// O(log n) via binary search over `sortedSpans`; the previous
    /// implementation scanned the entire address map on every register update.
    func location(forAddress address: UInt16) -> SourceLocation? {
        // Exact match first — the common case while stepping.
        if let loc = addressToLocation[address] { return loc }
        guard !sortedSpans.isEmpty else { return nil }

        // Largest index whose span starts at or before `address`.
        var lo = 0
        var hi = sortedSpans.count - 1
        var candidate = -1
        while lo <= hi {
            let mid = (lo + hi) / 2
            if sortedSpans[mid].start <= address {
                candidate = mid
                lo = mid + 1
            } else {
                hi = mid - 1
            }
        }
        guard candidate >= 0 else { return nil }

        // Spans can overlap (macros), so walk back looking for one that
        // actually contains `address`. Anything containing it must start at
        // or after `address - maxSpanLength + 1`, which bounds the walk.
        let earliestPossibleStart = Int(address) - maxSpanLength + 1
        var i = candidate
        while i >= 0 && Int(sortedSpans[i].start) >= earliestPossibleStart {
            if sortedSpans[i].end >= address { return sortedSpans[i].location }
            i -= 1
        }
        return nil
    }

    /// Returns the source file name for a file ID.
    func fileName(forId id: Int) -> String? {
        return files[id]?.name
    }

    /// Sets the primary file by name, matched on the last path component
    /// case-insensitively. Returns `true` if a matching file was found.
    ///
    /// Call this with the file the user is editing before resolving gutter
    /// breakpoints: without it the primary file is whichever one happens to
    /// contribute the most line mappings, which in a project with a large
    /// `.include` is not the file the breakpoints came from.
    @discardableResult
    func setPrimaryFile(named name: String) -> Bool {
        let want = (name as NSString).lastPathComponent.lowercased()
        for file in files.values {
            if (file.name as NSString).lastPathComponent.lowercased() == want {
                guard primaryFileId != file.id else { return true }
                primaryFileId = file.id
                // Pass 2's tie-break depends on the primary file, so redo it.
                rebuildAddressMap()
                return true
            }
        }
        return false
    }

    private func rebuildAddressMap() {
        addressToLocation.removeAll()
        for span in sortedSpans {
            guard let existing = addressToLocation[span.start] else {
                addressToLocation[span.start] = span.location
                continue
            }
            if preferredLocation(existing, span.location) == span.location {
                addressToLocation[span.start] = span.location
            }
        }
    }

    /// Returns the address for a named symbol.
    func addressForSymbol(_ name: String) -> UInt16? {
        return symbolsByName[name]?.address
    }

    /// Returns a summary string of the parsed debug information.
    var summary: String {
        let lineCount = fileLineToAddress.count
        let primaryName = primaryFileId
            .flatMap { files[$0]?.name }
            .map { " (primary: \(($0 as NSString).lastPathComponent))" } ?? ""
        let symCount = symbols.filter { !$0.name.hasPrefix("@") }.count
        let segNames = segments.values.map { $0.name }.joined(separator: ", ")
        return "\(lineCount) line mappings across \(files.count) file(s)\(primaryName), \(symCount) symbols, segments: \(segNames)"
    }

    // MARK: - Helpers

    private func intVal(_ str: String?) -> Int? {
        guard let s = str else { return nil }
        if s.hasPrefix("0x") || s.hasPrefix("0X") {
            return Int(s.dropFirst(2), radix: 16)
        }
        return Int(s)
    }

    private func hexVal(_ str: String?) -> Int? {
        guard let s = str else { return nil }
        if s.hasPrefix("0x") || s.hasPrefix("0X") {
            return Int(s.dropFirst(2), radix: 16)
        }
        return Int(s, radix: 16) ?? Int(s)
    }
}

// ═══════════════════════════════════════════════════════════
// MARK: - Data Structures
// ═══════════════════════════════════════════════════════════

/// Represents a source file referenced in the `.dbg` file.
struct DebugFile {
    let id: Int
    let name: String
}

/// Represents a memory segment (e.g., CODE, BSS, DATA).
struct DebugSegment {
    let id: Int
    let name: String
    let start: UInt16
}

/// Represents a contiguous byte range within a segment.
struct DebugSpan {
    let id: Int
    let segmentId: Int
    let offset: Int
    let size: Int
}

/// Maps a source line to one or more spans.
struct DebugLine {
    let fileId: Int
    let lineNumber: Int
    let spanIds: [Int]
}

/// A (file, line) pair identifying a location in source code.
struct SourceLocation: Hashable {
    let fileId: Int
    let line: Int
}

/// A span resolved to an inclusive absolute address range.
private struct MappedSpan {
    let start: UInt16
    let end: UInt16
    let location: SourceLocation
}

/// Represents a symbol (variable, function, label) with its address.
struct DebugSymbol {
    let name: String
    let address: UInt16
    let segmentId: Int?
}
