import Foundation

// ═══════════════════════════════════════════════════════════
// MARK: - DebugInfoParser
// ═══════════════════════════════════════════════════════════

/// Parses `.dbg` files generated by ca65/ld65 to map source lines
/// to memory addresses for source-level debugging.
///
/// `.dbg` format summary:
///   - `file`: Source file definitions with IDs
///   - `seg`: Segment definitions with start addresses
///   - `span`: Byte ranges within segments (offset + size)
///   - `line`: Source file line → span mapping
///   - `sym`: Symbol names → addresses
///
/// The parser builds bidirectional mappings (`fileLineToAddress` and
/// `addressToLocation`), keyed by (file, line) so multi-file projects
/// (.include) don't collide, to enable IDE features like breakpoint
/// setting and source highlighting.
class DebugInfoParser {

    // Parsed data
    private(set) var files: [Int: DebugFile] = [:]
    private(set) var segments: [Int: DebugSegment] = [:]
    private(set) var spans: [Int: DebugSpan] = [:]
    private(set) var lines: [DebugLine] = []
    private(set) var symbols: [DebugSymbol] = []

    // Derived mappings
    private(set) var fileLineToAddress: [SourceLocation: UInt16] = [:]  // (file, line) → memory address
    private(set) var addressToLocation: [UInt16: SourceLocation] = [:]  // memory address → (file, line)

    /// The file assumed when no explicit file is given (editor breakpoints,
    /// highlight callbacks). Defaults to the file contributing the most line
    /// mappings, which in practice is the main source. Override with
    /// `setPrimaryFile(named:)`.
    private(set) var primaryFileId: Int?
    private(set) var symbolsByName: [String: DebugSymbol] = [:]
    private(set) var symbolsByAddress: [UInt16: DebugSymbol] = [:]

    // MARK: - Parsing

    /// Parses a `.dbg` file and returns a configured parser instance.
    /// Returns `nil` if the file cannot be read.
    static func parse(contentsOf url: URL) -> DebugInfoParser? {
        guard let content = try? String(contentsOf: url, encoding: .utf8) else { return nil }
        let parser = DebugInfoParser()
        parser.parseContent(content)
        return parser
    }

    /// Parses a `.dbg` format string and returns a configured parser instance.
    static func parse(string: String) -> DebugInfoParser {
        let parser = DebugInfoParser()
        parser.parseContent(string)
        return parser
    }

    private func parseContent(_ content: String) {
        for rawLine in content.components(separatedBy: "\n") {
            let line = rawLine.trimmingCharacters(in: .whitespaces)
            guard !line.isEmpty else { continue }

            // Split into type and attributes
            guard let tabIndex = line.firstIndex(of: "\t") else { continue }
            let type = String(line[line.startIndex..<tabIndex])
            let attrs = String(line[line.index(after: tabIndex)...])
            let props = parseAttributes(attrs)

            switch type {
            case "file":    parseFile(props)
            case "seg":     parseSegment(props)
            case "span":    parseSpan(props)
            case "line":    parseLine(props)
            case "sym":     parseSymbol(props)
            default: break
            }
        }

        buildMappings()
    }

    // MARK: - Attribute Parser

    /// Parses `key=value,key=value,...` into a dictionary.
    /// Handles both quoted and unquoted values correctly.
    private func parseAttributes(_ str: String) -> [String: String] {
        var result: [String: String] = [:]

        var current = str.startIndex
        while current < str.endIndex {
            // Find key
            guard let eqIdx = str[current...].firstIndex(of: "=") else { break }
            let key = String(str[current..<eqIdx]).trimmingCharacters(in: .whitespaces)
            var valueStart = str.index(after: eqIdx)

            var value: String
            if valueStart < str.endIndex && str[valueStart] == "\"" {
                // Quoted value
                valueStart = str.index(after: valueStart)
                if let closeQuote = str[valueStart...].firstIndex(of: "\"") {
                    value = String(str[valueStart..<closeQuote])
                    current = str.index(after: closeQuote)
                } else {
                    value = String(str[valueStart...])
                    current = str.endIndex
                }
            } else {
                // Unquoted value — read until comma
                if let commaIdx = str[valueStart...].firstIndex(of: ",") {
                    value = String(str[valueStart..<commaIdx])
                    current = str.index(after: commaIdx)
                } else {
                    value = String(str[valueStart...])
                    current = str.endIndex
                }
            }

            result[key] = value

            // Skip comma
            if current < str.endIndex && str[current] == "," {
                current = str.index(after: current)
            }
        }

        return result
    }

    // MARK: - Entry Parsers

    private func parseFile(_ props: [String: String]) {
        guard let id = intVal(props["id"]),
              let name = props["name"] else { return }
        files[id] = DebugFile(id: id, name: name)
    }

    private func parseSegment(_ props: [String: String]) {
        guard let id = intVal(props["id"]),
              let name = props["name"],
              let start = hexVal(props["start"]),
              let size = hexVal(props["size"]),
              // Out-of-range start would trap UInt16(start); skip such segments
              (0...0xFFFF).contains(start) else { return }
        segments[id] = DebugSegment(id: id, name: name, start: UInt16(start), size: size)
    }

    private func parseSpan(_ props: [String: String]) {
        guard let id = intVal(props["id"]),
              let seg = intVal(props["seg"]),
              let start = intVal(props["start"]),
              let size = intVal(props["size"]) else { return }
        spans[id] = DebugSpan(id: id, segmentId: seg, offset: start, size: size)
    }

    private func parseLine(_ props: [String: String]) {
        guard let fileId = intVal(props["file"]),
              let lineNum = intVal(props["line"]) else { return }
        // ld65 emits multi-span lines as `span=286+287` (common with macros).
        // Parse every span so none of the line's code goes unmapped.
        let spanIds = props["span"]?
            .split(separator: "+")
            .compactMap { intVal(String($0)) } ?? []
        lines.append(DebugLine(fileId: fileId, lineNumber: lineNum, spanIds: spanIds))
    }

    private func parseSymbol(_ props: [String: String]) {
        // ca65 equates can be 32-bit or negative (stored as large hex values).
        // Anything outside the 6502 address space can't be a label or
        // breakpoint target and would trap UInt16(val), so skip it.
        guard let name = props["name"],
              let val = hexVal(props["val"]),
              (0...0xFFFF).contains(val) else { return }
        let segId = intVal(props["seg"])
        let size = intVal(props["size"])
        let sym = DebugSymbol(name: name, address: UInt16(val), segmentId: segId, size: size)
        symbols.append(sym)
    }

    // MARK: - Build Mappings

    private func buildMappings() {
        fileLineToAddress.removeAll()
        addressToLocation.removeAll()
        symbolsByName.removeAll()
        symbolsByAddress.removeAll()

        // Build (file, line) → address mapping
        for line in lines {
            for spanId in line.spanIds {
                guard let span = spans[spanId],
                      let seg = segments[span.segmentId] else { continue }

                // Compute in Int so a corrupt or oversized offset can't
                // trap UInt16(); addresses past $FFFF are skipped.
                let addrInt = Int(seg.start) + span.offset
                guard (0...0xFFFF).contains(addrInt) else { continue }
                let address = UInt16(addrInt)

                let loc = SourceLocation(fileId: line.fileId, line: line.lineNumber)

                // Only map if we don't have a mapping for this line yet,
                // or if this address is lower (first instruction on the line)
                if fileLineToAddress[loc] == nil || address < fileLineToAddress[loc]! {
                    fileLineToAddress[loc] = address
                }

                // Reverse mapping (prefer lower line numbers for the same address)
                if addressToLocation[address] == nil || loc.line < addressToLocation[address]!.line {
                    addressToLocation[address] = loc
                }
            }
        }

        // Default primary file: the one contributing the most line mappings.
        // (A user-set primary file survives re-parsing only if it still exists.)
        if primaryFileId == nil || files[primaryFileId!] == nil {
            var counts: [Int: Int] = [:]
            for loc in fileLineToAddress.keys { counts[loc.fileId, default: 0] += 1 }
            primaryFileId = counts.max(by: { $0.value < $1.value })?.key
        }

        // Build symbol mappings
        for sym in symbols {
            symbolsByName[sym.name] = sym
            // Only store non-local symbols (skip @ prefixed)
            if !sym.name.hasPrefix("@") {
                symbolsByAddress[sym.address] = sym
            }
        }
    }

    // MARK: - Queries

    /// Returns the memory address for a source line. When `fileId` is nil,
    /// the primary file is assumed (i.e. editor breakpoints in the main source).
    func addressForLine(_ line: Int, fileId: Int? = nil) -> UInt16? {
        guard let fid = fileId ?? primaryFileId else { return nil }
        return fileLineToAddress[SourceLocation(fileId: fid, line: line)]
    }

    /// Returns the source location (file + line) for a memory address.
    ///
    /// Performs an exact match first. If none exists, finds the closest
    /// address that is `≤` the given address, enabling approximate source
    /// highlighting for ranges spanning multiple instructions.
    func location(forAddress address: UInt16) -> SourceLocation? {
        // Exact match first
        if let loc = addressToLocation[address] { return loc }

        // Find the closest address that's ≤ the given address
        var bestLoc: SourceLocation?
        var bestAddr: UInt16 = 0
        for (addr, loc) in addressToLocation {
            if addr <= address && addr >= bestAddr {
                bestAddr = addr
                bestLoc = loc
            }
        }
        return bestLoc
    }

    /// Returns the primary-file source line for a memory address, or `nil`
    /// if the address maps into a different file (e.g. an include). Use
    /// `location(forAddress:)` when the file matters.
    func lineForAddress(_ address: UInt16) -> Int? {
        guard let loc = location(forAddress: address),
              loc.fileId == primaryFileId else { return nil }
        return loc.line
    }

    /// Returns the source file name for a file ID.
    func fileName(forId id: Int) -> String? {
        return files[id]?.name
    }

    /// Sets the primary file by name, matched on the last path component
    /// case-insensitively. Returns `true` if a matching file was found.
    @discardableResult
    func setPrimaryFile(named name: String) -> Bool {
        let want = (name as NSString).lastPathComponent.lowercased()
        for file in files.values {
            if (file.name as NSString).lastPathComponent.lowercased() == want {
                primaryFileId = file.id
                return true
            }
        }
        return false
    }

    /// Returns the address for a named symbol.
    func addressForSymbol(_ name: String) -> UInt16? {
        return symbolsByName[name]?.address
    }

    /// Returns all symbols defined within a specific segment.
    func symbolsInSegment(_ name: String) -> [DebugSymbol] {
        guard let seg = segments.values.first(where: { $0.name == name }) else { return [] }
        return symbols.filter { $0.segmentId == seg.id }
    }

    /// Converts editor breakpoint line numbers to memory addresses.
    func breakpointAddresses(forLines editorLines: Set<Int>) -> [UInt16] {
        var addresses: [UInt16] = []
        for line in editorLines.sorted() {
            if let addr = addressForLine(line) {
                addresses.append(addr)
            }
        }
        return addresses
    }

    /// Generates a VICE monitor commands file with breakpoints and labels.
    func generateMonitorCommands(breakpointLines: Set<Int>, entryPoint: UInt16? = nil) -> String {
        var cmds: [String] = ["; C64 IDE debug symbols"]

        // Add labels for all non-local symbols
        for sym in symbols where !sym.name.hasPrefix("@") {
            cmds.append(String(format: "al C:%04X .%@", sym.address, sym.name))
        }

        cmds.append("")

        // Entry point breakpoint
        if let entry = entryPoint {
            cmds.append(String(format: "break $%04x", entry))
        }

        // Editor breakpoints mapped to addresses
        for line in breakpointLines.sorted() {
            if let addr = addressForLine(line) {
                cmds.append(String(format: "break $%04x  ; line %d", addr, line))
            }
        }

        return cmds.joined(separator: "\n") + "\n"
    }

    /// Returns a summary string of the parsed debug information.
    var summary: String {
        let lineCount = fileLineToAddress.count
        let primaryName = primaryFileId
            .flatMap { files[$0]?.name }
            .map { " (primary: \(($0 as NSString).lastPathComponent))" } ?? ""
        let symCount = symbols.filter { !$0.name.hasPrefix("@") }.count
        let segNames = segments.values.map { $0.name }.joined(separator: ", ")
        return "\(lineCount) line mappings across \(files.count) file(s)\(primaryName), \(symCount) symbols, segments: \(segNames)"
    }

    // MARK: - Helpers

    private func intVal(_ str: String?) -> Int? {
        guard let s = str else { return nil }
        if s.hasPrefix("0x") || s.hasPrefix("0X") {
            return Int(s.dropFirst(2), radix: 16)
        }
        return Int(s)
    }

    private func hexVal(_ str: String?) -> Int? {
        guard let s = str else { return nil }
        if s.hasPrefix("0x") || s.hasPrefix("0X") {
            return Int(s.dropFirst(2), radix: 16)
        }
        return Int(s, radix: 16) ?? Int(s)
    }
}

// ═══════════════════════════════════════════════════════════
// MARK: - Data Structures
// ═══════════════════════════════════════════════════════════

/// Represents a source file referenced in the `.dbg` file.
struct DebugFile {
    let id: Int
    let name: String
}

/// Represents a memory segment (e.g., CODE, BSS, DATA).
struct DebugSegment {
    let id: Int
    let name: String
    let start: UInt16
    let size: Int
}

/// Represents a contiguous byte range within a segment.
struct DebugSpan {
    let id: Int
    let segmentId: Int
    let offset: Int
    let size: Int
}

/// Maps a source line to one or more spans.
struct DebugLine {
    let fileId: Int
    let lineNumber: Int
    let spanIds: [Int]
}

/// A (file, line) pair identifying a location in source code.
struct SourceLocation: Hashable {
    let fileId: Int
    let line: Int
}

/// Represents a symbol (variable, function, label) with its address.
struct DebugSymbol {
    let name: String
    let address: UInt16
    let segmentId: Int?
    let size: Int?
}

